# Home Assistant Add-on Configuration
name: "HA Screenshotter"
version: "1.1.0"
slug: "ha-screenshotter"
description: "Takes screenshots of web pages on a configurable schedule with rotation, grayscale, and bit depth support"
url: "https://github.com/jantielens/ha-screenshotter"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
map:
  - "config/www:rw"
options:
  schedule: "* * * * *"
  urls: '["https://google.com", "https://time.now/"]'
  resolution_width: 1920
  resolution_height: 1080
  rotation_degrees: 0
  grayscale: false
  bit_depth: 24
schema:
  schedule: str?
  urls: str?
  resolution_width: int?
  resolution_height: int?
  rotation_degrees: int?
  grayscale: bool?
  bit_depth: int?