# Alternative sample configuration using object format for URLs
# This format allows you to use URLs as keys for cleaner configuration

schedule: "*/5 * * * *"
resolution_width: 1920
resolution_height: 1080

# Using object format for URLs (alternative to array format)
urls: '{
  "https://simple-url.com": {},
  "https://custom-size.com": {
    "width": 1280,
    "height": 720
  },
  "https://home-assistant-dashboard.local:8123/dashboard-mobile": {
    "width": 375,
    "height": 812,
    "crop": {
      "x": 0,
      "y": 44,
      "width": 375,
      "height": 700
    }
  },
  "https://grafana.local/dashboard": {
    "width": 1920,
    "height": 1080,
    "crop": {
      "x": 200,
      "y": 100,
      "width": 1520,
      "height": 900
    }
  },
  "https://weather-widget.com": {
    "width": 1920,
    "height": 1080,
    "rotation": 0,
    "crop": {
      "x": 10,
      "y": 10,
      "width": 400,
      "height": 300
    },
    "grayscale": false,
    "bit_depth": 24
  }
}'

long_lived_access_token: "your_token_here"
run_once: false
webserverport: 0