# Simple test configuration for crop functionality
# This configuration demonstrates basic cropping with safe, common websites

schedule: "0 */6 * * *"  # Every 6 hours for testing
resolution_width: 1280
resolution_height: 720
rotation_degrees: 0
grayscale: false  
bit_depth: 24
crop: null  # No global cropping

urls: '[
  {
    "url": "https://example.com",
    "width": 1280,
    "height": 720,
    "crop": {
      "x": 100,
      "y": 100,
      "width": 400,
      "height": 300
    }
  },
  {
    "url": "https://httpbin.org/html",
    "width": 1280, 
    "height": 720,
    "crop": {
      "x": 0,
      "y": 0,
      "width": 640,
      "height": 360
    }
  }
]'

long_lived_access_token: ""
run_once: true  # Run once for testing
webserverport: 0
language: "en"