name: 'Setup Test Environment'
description: 'Setup Docker and tools for ha-screenshotter testing'
inputs:
  docker-image-name:
    description: 'Name for the Docker image to build'
    required: true
  working-directory:
    description: 'Directory containing the Dockerfile'
    required: false
    default: 'ha-screenshotter'
runs:
  using: "composite"
  steps:
    - name: Install ImageMagick and tools
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick jq bc

    - name: Build Docker container
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        docker build -t ${{ inputs.docker-image-name }} .
